import type { Contract, ContractMatch } from '@/types'

export const MOCK_CONTRACTS: Contract[] = [
  {
    id: 'mock-1',
    title: 'IT Infrastructure Maintenance and Support Services',
    agency: 'Department of Veterans Affairs',
    location: 'Washington, DC',
    state: 'DC',
    due_date: '2026-08-15',
    value_min: 250000,
    value_max: 500000,
    source_name: 'SAM.gov',
    description:
      'The Department of Veterans Affairs seeks qualified contractors to provide comprehensive IT infrastructure maintenance including server management, network monitoring, and help desk support for VA facilities in the Washington DC metropolitan area. Services include 24/7 NOC operations, patch management, and disaster recovery planning.',
    requirements: [
      'Must hold an active SDVOSB or VOSB certification',
      'Minimum 5 years of federal IT service experience',
      'FISMA compliance experience required',
      'Must be able to obtain facility access clearances',
      'ISO 27001 or NIST 800-53 familiarity preferred',
    ],
    naics_codes: ['541512', '541519'],
    certifications_required: ['SDVOSB', 'VOSB'],
    solicitation_number: 'VA-36C10X26R0042',
    posted_date: '2026-06-01',
  },
  {
    id: 'mock-2',
    title: 'Cybersecurity Assessment and Monitoring Services',
    agency: 'Department of Homeland Security',
    location: 'Arlington, VA',
    state: 'VA',
    due_date: '2026-07-30',
    value_min: 500000,
    value_max: 2000000,
    source_name: 'SAM.gov',
    description:
      'DHS is seeking a contractor to perform ongoing cybersecurity assessments, penetration testing, and continuous monitoring services for agency networks. The scope includes vulnerability management, incident response, and security awareness training for DHS personnel.',
    requirements: [
      '8(a) or small business set-aside eligibility required',
      'CISSP or equivalent certifications for key personnel',
      'Experience with federal SIEM tools (Splunk, QRadar)',
      'Active secret clearance required for all staff',
    ],
    naics_codes: ['541512', '541519', '561621'],
    certifications_required: ['8(a)', 'SDB'],
    solicitation_number: 'DHS-26-B-00173',
    posted_date: '2026-05-28',
  },
  {
    id: 'mock-3',
    title: 'General Construction and Renovation Services — Federal Buildings',
    agency: 'General Services Administration',
    location: 'Atlanta, GA',
    state: 'GA',
    due_date: '2026-09-01',
    value_min: 1000000,
    value_max: 5000000,
    source_name: 'SAM.gov',
    description:
      'GSA Public Buildings Service requires general construction and renovation services for federal office buildings in the Atlanta region. Work includes interior renovations, ADA compliance upgrades, HVAC replacement, and energy efficiency improvements across multiple facilities.',
    requirements: [
      'Licensed general contractor in Georgia',
      'Davis-Bacon Act compliance required',
      'Bonding and insurance per FAR 28.102',
      'HUBZone or WOSB preferred',
      'LEED experience a plus',
    ],
    naics_codes: ['236220', '238210', '238220'],
    certifications_required: ['HUBZone', 'WOSB'],
    solicitation_number: 'GS-04P-26-HJ-C-0019',
    posted_date: '2026-06-05',
  },
  {
    id: 'mock-4',
    title: 'Healthcare Staffing and Workforce Solutions',
    agency: 'Department of Health and Human Services',
    location: 'Rockville, MD',
    state: 'MD',
    due_date: '2026-08-01',
    value_min: 750000,
    value_max: 3000000,
    source_name: 'SAM.gov',
    description:
      'HHS seeks qualified staffing firms to provide temporary and permanent healthcare professionals including registered nurses, medical assistants, and administrative staff across multiple HHS facilities. Contract includes workforce planning consultation and credentialing services.',
    requirements: [
      'Joint Commission accreditation preferred',
      'WOSB or MBE certification preferred',
      'Background screening and credentialing process in place',
      'Experience placing staff in federal health facilities',
    ],
    naics_codes: ['561320', '621111', '621610'],
    certifications_required: ['WOSB', 'MBE'],
    solicitation_number: 'HHS-2026-NIH-SS-0047',
    posted_date: '2026-06-10',
  },
  {
    id: 'mock-5',
    title: 'Environmental Site Assessment and Remediation',
    agency: 'Environmental Protection Agency',
    location: 'Denver, CO',
    state: 'CO',
    due_date: '2026-07-15',
    value_min: 300000,
    value_max: 1200000,
    source_name: 'SAM.gov',
    description:
      'EPA Region 8 is seeking qualified environmental consulting firms to conduct Phase I and Phase II site assessments, groundwater monitoring, and remediation at Superfund sites across Colorado, Utah, Wyoming, Montana, North Dakota, and South Dakota.',
    requirements: [
      'Licensed Professional Geologist or Environmental Engineer on staff',
      'Experience with CERCLA remediation projects',
      'OSHA HAZWOPER 40-hour training for field staff',
      'DBE or small business preferred',
    ],
    naics_codes: ['541620', '562910', '541380'],
    certifications_required: ['DBE', 'SDB'],
    solicitation_number: 'EPA-R8-26-C-00211',
    posted_date: '2026-05-15',
  },
  {
    id: 'mock-6',
    title: 'Professional Training and Development Services',
    agency: 'Office of Personnel Management',
    location: 'Washington, DC',
    state: 'DC',
    due_date: '2026-09-15',
    value_min: 150000,
    value_max: 600000,
    source_name: 'SAM.gov',
    description:
      'OPM is seeking contractors to deliver leadership development, project management, and technical skills training to federal employees. Training may be delivered in-person, virtually, or in hybrid format. Curriculum development and LMS administration are in scope.',
    requirements: [
      '8(a) or WOSB set-aside eligibility',
      'Certified instructional designers on staff (ATD or CPLP)',
      'Experience with federal learning management systems',
      'Section 508 compliant course delivery',
    ],
    naics_codes: ['611430', '611699', '541611'],
    certifications_required: ['8(a)', 'WOSB'],
    solicitation_number: 'OPM-HR-SOLHQ-26-0033',
    posted_date: '2026-06-12',
  },
  {
    id: 'mock-7',
    title: 'Logistics and Supply Chain Support Services',
    agency: 'Defense Logistics Agency',
    location: 'Fort Belvoir, VA',
    state: 'VA',
    due_date: '2026-08-22',
    value_min: 2000000,
    value_max: 8000000,
    source_name: 'SAM.gov',
    description:
      'DLA seeks a contractor to provide comprehensive logistics support including warehouse management, inventory control, transportation coordination, and supply chain analytics for DLA distribution centers on the East Coast. Clearance required for some task orders.',
    requirements: [
      'SDVOSB or VOSB certification required for set-aside',
      'Experience with DLA business systems (EBS)',
      'ISO 9001:2015 certification preferred',
      'Bonded and insured per DOD requirements',
    ],
    naics_codes: ['488510', '492110', '493110'],
    certifications_required: ['SDVOSB', 'VOSB'],
    solicitation_number: 'SP4705-26-R-0091',
    posted_date: '2026-06-08',
  },
  {
    id: 'mock-8',
    title: 'Janitorial and Facility Cleaning Services',
    agency: 'Army Corps of Engineers',
    location: 'Seattle, WA',
    state: 'WA',
    due_date: '2026-07-01',
    value_min: 80000,
    value_max: 250000,
    source_name: 'SAM.gov',
    description:
      'The Army Corps of Engineers requires comprehensive janitorial and facility cleaning services at the Seattle District headquarters and field offices. Services include daily cleaning, floor care, window washing, and restocking of consumable supplies.',
    requirements: [
      'HUBZone or small business set-aside eligibility',
      'Background checks for all facility access personnel',
      'Green cleaning product compliance preferred',
      'Bond and liability insurance required',
    ],
    naics_codes: ['561720', '561790'],
    certifications_required: ['HUBZone'],
    solicitation_number: 'W912DW-26-B-0028',
    posted_date: '2026-05-30',
  },
  {
    id: 'mock-dibbs-1',
    title: 'Helicopter Rotor Blade Assembly — NSN 1615-01-430-1290',
    agency: 'Defense Logistics Agency',
    location: 'Richmond, VA',
    state: 'VA',
    due_date: '2026-07-25',
    value_min: 50000,
    value_max: 250000,
    source_name: 'DIBBS',
    source_url: 'https://www.dibbs.bsm.dla.mil/Rfp/RfpSol.aspx?sn=SPE4AX-26-Q-0847',
    description:
      'DLA Aviation seeks qualified suppliers for helicopter rotor blade assemblies. Items must meet MIL-SPEC requirements and DLA source approval. FSC 1615 — Aircraft Propellers and Components. Quantity: 12 EA.',
    requirements: [
      'AS9100D aerospace quality certification required',
      'DLA source approval required prior to award',
      'CAGE code registration on SAM.gov required',
      'FAA Production Approval Holder (PAH) preferred',
    ],
    naics_codes: ['336413'],
    fsc_codes: ['1615'],
    nsn: '1615-01-430-1290',
    solicitation_type: 'Competitive',
    certifications_required: ['SDB'],
    solicitation_number: 'SPE4AX-26-Q-0847',
    posted_date: '2026-06-15',
  },
  {
    id: 'mock-dibbs-2',
    title: 'Electronic Resistor Assembly — NSN 5905-01-221-8477',
    agency: 'Defense Logistics Agency',
    location: 'Columbus, OH',
    state: 'OH',
    due_date: '2026-08-10',
    value_min: 15000,
    value_max: 80000,
    source_name: 'DIBBS',
    source_url: 'https://www.dibbs.bsm.dla.mil/Rfp/RfpSol.aspx?sn=SPE7M3-26-T-3491',
    description:
      'DLA Land and Maritime requires electronic resistor assemblies to MIL-PRF-55182 specification. FSC 5905 — Resistors. Qualification testing per MIL-STD-202 required. Quantity: 500 EA.',
    requirements: [
      'ITAR registered manufacturer required',
      'QPL listed or qualified products preferred',
      'Certificate of conformance required with delivery',
    ],
    naics_codes: ['334416'],
    fsc_codes: ['5905'],
    nsn: '5905-01-221-8477',
    solicitation_type: 'Sole Source',
    certifications_required: [],
    solicitation_number: 'SPE7M3-26-T-3491',
    posted_date: '2026-06-20',
  },
  {
    id: 'mock-tx-1',
    title: 'Road Maintenance Equipment Rental',
    agency: 'Texas Department of Transportation',
    location: 'Austin, TX',
    state: 'TX',
    due_date: '2026-07-18',
    value_min: 100000,
    value_max: 400000,
    source_name: 'Texas SmartBuy',
    description:
      'TxDOT seeks vendors to provide heavy equipment rental for road maintenance operations statewide. Equipment includes motor graders, rollers, and dump trucks. Short-term and long-term rental agreements.',
    requirements: [
      'HUB certification preferred for set-aside consideration',
      'Equipment must meet TXDOT safety standards',
      'Liability insurance minimum $1M required',
    ],
    naics_codes: ['532412', '532490'],
    certifications_required: ['DBE', 'MBE'],
    solicitation_number: 'TXDOT-2026-0441',
    posted_date: '2026-06-10',
  },
  {
    id: 'mock-hou-1',
    title: 'Parks and Recreation Landscaping Services',
    agency: 'City of Houston Parks & Recreation',
    location: 'Houston, TX',
    state: 'TX',
    due_date: '2026-08-05',
    value_min: 200000,
    value_max: 800000,
    source_name: 'City of Houston',
    description:
      'The City of Houston seeks qualified landscaping contractors for mowing, planting, irrigation maintenance, and grounds keeping across 300+ city parks. Multi-year contract with annual renewals.',
    requirements: [
      'MWBE certification encouraged',
      'Licensed irrigator required for irrigation scope',
      'Workers compensation insurance required',
    ],
    naics_codes: ['561730', '561730'],
    certifications_required: ['MBE', 'DBE'],
    solicitation_number: 'COH-PARKS-2026-117',
    posted_date: '2026-06-18',
  },
  {
    id: 'mock-hc-1',
    title: 'Fleet Vehicle Maintenance Services',
    agency: 'Harris County Fleet Services',
    location: 'Houston, TX',
    state: 'TX',
    due_date: '2026-07-28',
    value_min: 500000,
    value_max: 2000000,
    source_name: 'Harris County',
    description:
      'Harris County Fleet Services seeks qualified mechanics and service facilities for preventive maintenance, repair, and inspection of county fleet vehicles including patrol cars, heavy equipment, and light-duty trucks.',
    requirements: [
      'ASE Certified Master Technician on staff required',
      'Service facility within 30 miles of Houston required',
      'MWBE certification preferred',
    ],
    naics_codes: ['811111', '811112', '811198'],
    certifications_required: ['MBE'],
    solicitation_number: 'HC-FLEET-2026-0092',
    posted_date: '2026-06-14',
  },
]

export function generateMockMatches(profileId: string): ContractMatch[] {
  const matchData = [
    {
      contractId: 'mock-1',
      score: 94,
      reasons: [
        'Your NAICS code 541512 directly matches this IT services contract',
        'Service radius covers the Washington DC metro area',
        'Past government experience is a strong alignment signal',
        'Years in business meet the minimum experience requirement',
      ],
      steps: [
        "Register on SAM.gov if you haven't already — required to bid",
        'Obtain your DUNS/UEI number from SAM.gov',
        'Download the solicitation from beta.SAM.gov using the solicitation number',
        'Prepare a capability statement tailored to VA IT requirements',
        'Contact the contracting officer listed in the solicitation for a pre-submission Q&A',
      ],
    },
    {
      contractId: 'mock-2',
      score: 81,
      reasons: [
        'Cybersecurity NAICS codes align with your IT services profile',
        'Your certifications qualify you for the small business set-aside',
        'DHS location is within your service radius',
      ],
      steps: [
        'Verify your clearance sponsorship capability before bidding',
        'Review NIST 800-53 compliance documentation',
        'Prepare key personnel resumes highlighting relevant certifications',
        'Attend any posted industry day events for this solicitation',
      ],
    },
    {
      contractId: 'mock-dibbs-1',
      score: 76,
      reasons: [
        'FSC code 1615 matches your aerospace parts supply capability',
        'This NSN is in your tracked NSN interest list',
        'DLA Aviation is within your service area',
      ],
      steps: [
        'Confirm your DLA source approval status for NSN 1615-01-430-1290',
        'Register or verify your CAGE code on SAM.gov',
        'Submit a quote through DIBBS before the closing date',
        'Prepare a certificate of conformance and quality plan',
      ],
    },
    {
      contractId: 'mock-6',
      score: 77,
      reasons: [
        'Professional services NAICS codes are a partial match',
        'Your certifications align with the WOSB set-aside preference',
        'Federal customer experience is valued by OPM',
      ],
      steps: [
        'Develop a sample training curriculum to include in your proposal',
        'Highlight any LMS platform experience in your capability statement',
        'Review Section 508 accessibility requirements',
      ],
    },
    {
      contractId: 'mock-4',
      score: 68,
      reasons: [
        'Professional services background is a partial match',
        'Certification preferences align with your profile',
        'Location is within a reasonable service radius',
      ],
      steps: [
        'Consider partnering with a healthcare staffing firm for this bid',
        'Review Joint Commission accreditation requirements',
        'Prepare past performance references in the healthcare domain',
      ],
    },
  ]

  return matchData.map((m, i) => ({
    id: `mock-match-${i + 1}`,
    business_profile_id: profileId,
    contract_id: m.contractId,
    match_score: m.score,
    match_reasons: m.reasons,
    suggested_next_steps: m.steps,
    contract: MOCK_CONTRACTS.find((c) => c.id === m.contractId),
  }))
}

export function getMockContractById(id: string): Contract | undefined {
  return MOCK_CONTRACTS.find((c) => c.id === id)
}

export function getMockMatchByContractId(
  contractId: string,
  profileId = 'mock'
): ContractMatch | undefined {
  return generateMockMatches(profileId).find(
    (m) => m.contract_id === contractId
  )
}
